apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: score-board-app-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/taofeekaoyusuf/score-board-app.git'
    targetRevision: HEAD
    path: argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true